#:kivy 1.10.0








<MenuScreen>:
    BoxLayout:
        orientation: 'horizontal'

        
        Button:
            text: 'Goto settings'
            on_press:
                root.manager.transition.direction = 'left'
                root.manager.current = 'settings'
        # Button:
        #     text: 'Quit'
        #     on_press:
        #         root.manager.Quit




<SettingsScreen>:
    BoxLayout:
        Button:
            text: 'My settings button'
        Button:
            text: 'Back to menu'
            on_press:
                root.manager.transition.direction = 'right'
                root.manager.current = 'menu'













# <PageLayout>

#     # Creating Page 1
     
#     # Using BoxLayout inside PageLayout
#     BoxLayout:

#         # Providing orientation to the BoxLayout
#         orientation: 'vertical'
 
#         # Background
#         Widget:
#             size_hint: None, None
#             size: 500, 500
#             pos: 200, 200
#             canvas:
#                 Color:
#                     rgba: 255 / 255., 100 / 255., 88 / 255., 1
#                 RoundedRectangle:
#                     pos: root.pos
#                     size: self.size
#                     radius: [20,]
            


#         # This is the title text in the top left
#         RelativeLayout:
        
#             size_hint: 1, None
#             height: 150
#             canvas:
#                 Color:
#                     rgba: 0 / 255., 100 / 255., 88 / 255., 1
#                 RoundedRectangle:
#                     size: 400, root.size[1]
#                     radius: [20,]

#             # Drop Shadow
#             Label:
#                 size_hint_y: None
#                 height: 1.5 * self.texture_size[1]
#                 font_size: '30sp'
#                 text: 'BUTM DDS'
#                 # pos_hint: {'center_x': 0.5, 'center_y': 0.5}
#                 # pos_hint: {'center_x': 0, 'center_y': 0.5}
#                 # pos_hint: {'center_x': 0}
#                 pos: (root.x-root.width/2.0) + 253, -3
                
#                 color: 0, 0, 0, 1  # White color for text
#                 font_name: 'Fonts/Arial-Bold.ttf'

                
#             # Regular Text
#             Label:
#                 size_hint_y: None
#                 height: 1.5 * self.texture_size[1]
#                 font_size: '30sp'
#                 text: 'BUTM DDS'
#                 # pos_hint: {'center_x': 0.5, 'center_y': 0.5}
#                 # pos_hint: {'center_x': 0, 'center_y': 0.5}
#                 # pos_hint: {'center_x': 0}
#                 pos: (root.x-root.width/2.0) + 250, 0
                
#                 color: 1, 1, 1, 1  # White color for text
#                 font_name: 'Fonts/Arial-Bold.ttf'

                

        
        
#         BoxLayout:
#             orientation: 'horizontal'
#             size_hint: 1, 1
        
        
        
#         # Creating Button
#         Button:
#             text: 'GFG :)'
#             size_hint_y: 0
#             height: 50  # Adjust the height as needed
             
#             # Adding On_press function
#             # i.e binding function to press / touch
#             on_press: print("This Is The First Page")